post http://localhost:5000/api/posts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYW51ZWxlQGdtYWlsLmNvbSIsImlkIjoiNjI5MDhhZDhkYmQyMTY0NWRlNTU3ODU3IiwiaWF0IjoxNjUzNzAzNzE5LCJleHAiOjE2NTM3MDczMTl9.rcLQ7_Q-2Q9TwzN46UC9uhcFJ-Tvr9xopKkhwetHJvY

{
    "title": "let's see if this works",
    "creator": "manu"
}