delete http://localhost:5000/api/posts/628c98b8f7e3b1d0e6d3a349
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYW51ZWxlQGdtYWlsLmNvbSIsImlkIjoiNjI4YzgwMTJiZDRiNjVkZWZhZGFmNWM4IiwiaWF0IjoxNjUzMzgxNDE5LCJleHAiOjE2NTMzODUwMTl9.3Q8rpX-1aWEB1VlV-oAd2vnhOf9dVzORk2IaJGtWZ9c